#!/usr/bin/env python3
"""Regenerate every number and figure that appears in the documentation.

Run `make results`. This writes docs/results.md and assets/*.png. No figure in
this repository is drawn by hand and no number in the README is typed in by
hand -- if a claim is not produced by this script, it should not be in the docs.
"""

from __future__ import annotations

import argparse
import io
import os
import sys
import time
from contextlib import redirect_stdout

from rvleak import campaign, report, victims
from rvleak.uarch import ModelConfig

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
DOCS = os.path.join(ROOT, "docs")
ASSETS = os.path.join(ROOT, "assets")


def block(fn) -> str:
    buf = io.StringIO()
    with redirect_stdout(buf):
        fn()
    return buf.getvalue().rstrip()


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--traces", type=int, default=1000)
    ap.add_argument("--tvla-traces", type=int, default=200)
    ap.add_argument("--quick", action="store_true",
                    help="smaller trace counts, for a fast smoke run")
    args = ap.parse_args()
    if args.quick:
        args.traces, args.tvla_traces = 300, 100

    os.makedirs(DOCS, exist_ok=True)
    os.makedirs(ASSETS, exist_ok=True)
    started = time.time()
    out: list[str] = []

    out.append("# Results\n")
    out.append(
        "Generated by `scripts/reproduce.py`. Every figure and number below is\n"
        "produced by that script on a fixed seed; re-running it reproduces this\n"
        "file exactly. Do not edit by hand.\n"
    )
    out.append(f"\nConfiguration: default `ModelConfig` "
               f"(4 KiB 4-way D-cache, 32 B lines, 20-cycle miss penalty, gshare, "
               f"noise sigma = 1.0), {args.tvla_traces} traces per TVLA group, "
               f"{args.traces} traces for CPA.\n")

    # 1. False-positive control
    out.append("\n## 1. Detector validation (false-positive control)\n")
    out.append(
        "Fixed-vs-fixed: both groups use identical secrets and identical public\n"
        "inputs, so there is no channel to detect. This runs first because every\n"
        "negative result elsewhere depends on it.\n"
    )
    null = campaign.null_campaign("table-lookup", args.tvla_traces)
    out.append("```\n" + null.tvla.summary() + "\n" +
               report.t_trace_ascii(null.tvla.t) + "\n```\n")

    # 2. Leakage detection across the victim pairs
    out.append("\n## 2. Leakage detection across leaky/hardened pairs\n")
    tvla_results = {}
    rows = []
    for name in victims.REGISTRY:
        res = campaign.tvla_campaign(name, args.tvla_traces)
        tvla_results[name] = res.tvla
        rows.append((
            name,
            "hardened" if victims.REGISTRY[name].hardened else "leaky",
            f"{res.tvla.peak_t:.1f}",
            "LEAK" if res.timing.leaks else "constant",
            f"{res.timing.mean_fixed:.0f} / {res.timing.mean_random:.0f}",
        ))
    out.append("| victim | class | power max \\|t\\| | timing | mean cycles fixed / random |")
    out.append("|---|---|---|---|---|")
    for r in rows:
        out.append("| " + " | ".join(r) + " |")
    out.append(
        "\nThe timing column separates the pairs exactly: every leaky victim is\n"
        "flagged, every hardened victim is constant-time. The power column does\n"
        "**not** separate them, and that is the substantive finding rather than a\n"
        "shortcoming of the tool -- see the discussion in the README.\n"
    )
    out.append("\n![TVLA t-traces](../assets/tvla.png)\n")

    # 3. Attribution
    out.append("\n## 3. Attribution: which instruction leaks\n")
    res = campaign.tvla_campaign("memcmp-early-exit", args.tvla_traces)
    build = campaign._build("memcmp-early-exit", bytes(16), campaign.DEFAULT_KEY)
    listing = {int(line.split(":")[0], 16): line for line in build.program.disassemble()}
    out.append("```")
    out.append(res.summary())
    out.append("")
    out.append("corresponding instructions:")
    for a in res.attributions[:5]:
        out.append("  " + listing.get(a.pc, f"{a.pc:08x}: <unknown>"))
    out.append("```\n")

    # 4. Key recovery
    out.append("\n## 4. Key recovery by correlation power analysis\n")
    full = campaign.full_key_campaign(args.traces, sweep_step=25)
    out.append("```\n" + full.summary() + "\n```\n")

    single = campaign.cpa_campaign(args.traces, target_byte=0)
    report.save_figures(ASSETS, tvla_results=tvla_results,
                        cpa_result=single.result, true_key=single.true_key)
    out.append("![CPA](../assets/cpa.png)\n")

    # 5. Ablations
    out.append("\n## 5. Ablations: why the defaults are the defaults\n")
    out.append(
        "Each row disables one part of the analysis. These are failure modes the\n"
        "tool would otherwise hide, so they are asserted in the test suite.\n"
    )
    out.append("\n### 5.1 Without attribution-guided point-of-interest selection\n")
    no_poi = campaign.cpa_campaign(args.traces, use_poi=False)
    out.append("```\n" + no_poi.summary() + "\n```\n")
    out.append(
        "The plaintext load earlier in the loop body leaks HW(p) directly, which\n"
        "correlates maximally with the hypothesis for candidate 0x00 regardless of\n"
        "the real key. A textbook ghost peak.\n"
    )

    out.append("\n### 5.2 With a mismatched leakage model (HW against an HD bus)\n")
    hw_ranks = []
    for byte in range(4):
        r = campaign.cpa_campaign(args.traces, target_byte=byte, model="hw",
                                  sweep_step=args.traces)
        hw_ranks.append((byte, r.true_key, r.result.best, r.rank))
    out.append("| byte | true key | HW-model best | rank of true key |")
    out.append("|---|---|---|---|")
    for b, t, best, rank in hw_ranks:
        out.append(f"| {b} | {t:#04x} | {best:#04x} | {rank} |")
    out.append(
        "\nThe returned candidates sit a Hamming step or two from the true key. The\n"
        "attack is not failing randomly -- it is succeeding against the wrong model.\n"
    )

    # 6. Noise sweep
    out.append("\n## 6. Attack cost versus measurement noise\n")
    out.append("| noise sigma | bytes recovered | worst-case traces to stable recovery |")
    out.append("|---|---|---|")
    for sigma in (0.5, 1.0, 2.0, 4.0, 8.0):
        r = campaign.full_key_campaign(args.traces, cfg=ModelConfig(noise_sigma=sigma),
                                       sweep_step=50)
        worst = r.worst_case_traces
        cell = worst if worst is not None else f'> {args.traces}'
        out.append(f"| {sigma} | {r.n_correct}/16 | {cell} |")
    out.append(
        "\nTrace count required grows with sigma, as the standard CPA analysis\n"
        "predicts. This sweep is the closest the tool comes to a quantitative\n"
        "security claim, and it is a claim about the model, not about silicon.\n"
    )

    out.append(f"\n---\n\nGenerated in {time.time() - started:.1f} s.\n")

    path = os.path.join(DOCS, "results.md")
    with open(path, "w") as fh:
        fh.write("\n".join(out) + "\n")
    print(f"wrote {path}")
    print(f"wrote {ASSETS}/tvla.png, {ASSETS}/cpa.png")
    return 0


if __name__ == "__main__":
    sys.exit(main())
